{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b3ddaa33-8134-4a57-9cd5-2d374c542f4a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to database\n",
      "Database connection successful.\n"
     ]
    }
   ],
   "source": [
    "# =====================================================\n",
    "# HOSPITAL MANAGEMENT SYSTEM – COMPLETE WORKING VERSION\n",
    "# =====================================================\n",
    "\n",
    "import sys, subprocess, importlib, threading, os, datetime as dt\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "# Auto-install missing packages\n",
    "required_pkgs = ['pyodbc', 'customtkinter', 'pillow', 'matplotlib', 'pandas', 'openpyxl', 'fpdf']\n",
    "for pkg in required_pkgs:\n",
    "    try:\n",
    "        importlib.import_module(pkg)\n",
    "    except ImportError:\n",
    "        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg])\n",
    "\n",
    "import tkinter as tk\n",
    "from tkinter import ttk, messagebox\n",
    "import pyodbc\n",
    "import customtkinter as ctk\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg\n",
    "import pandas as pd\n",
    "from fpdf import FPDF\n",
    "from PIL import Image\n",
    "\n",
    "# ========== DATABASE CONNECTION ==========\n",
    "# Change this if your SQL Server instance is different (e.g., \"localhost\" for default instance)\n",
    "SERVER = r\"localhost\\SQLEXPRESS\"   # For SQL Server Express\n",
    "DATABASE = \"Hospital_Final_Project\"\n",
    "\n",
    "def get_connection_string():\n",
    "    for driver in [\"{ODBC Driver 18 for SQL Server}\", \"{ODBC Driver 17 for SQL Server}\", \n",
    "                   \"{ODBC Driver 13 for SQL Server}\", \"{SQL Server}\"]:\n",
    "        conn_str = f\"DRIVER={driver};SERVER={SERVER};DATABASE={DATABASE};Trusted_Connection=yes;TrustServerCertificate=yes;\"\n",
    "        try:\n",
    "            conn = pyodbc.connect(conn_str, timeout=5)\n",
    "            conn.close()\n",
    "            return conn_str\n",
    "        except:\n",
    "            continue\n",
    "    raise Exception(\"No suitable ODBC driver found. Check SQL Server and driver installation.\")\n",
    "\n",
    "CONN_STR = get_connection_string()\n",
    "print(\"Connected to database\")\n",
    "\n",
    "def query_db(query, params=(), fetch_all=True):\n",
    "    conn = pyodbc.connect(CONN_STR)\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(query, params)\n",
    "    is_select = query.strip().upper().startswith(('SELECT', 'WITH'))\n",
    "    if is_select:\n",
    "        result = cursor.fetchall() if fetch_all else cursor.fetchone()\n",
    "    else:\n",
    "        result = None\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "    return result\n",
    "\n",
    "def sanitize_row(row):\n",
    "    return [str(v).replace('(', '').replace(')', '').replace(',', ' ') if v is not None else \"\" for v in row]\n",
    "\n",
    "def export_to_excel(treeview, filename):\n",
    "    data = []\n",
    "    columns = [treeview.heading(c)['text'] for c in treeview['columns']]\n",
    "    for child in treeview.get_children():\n",
    "        row = treeview.item(child)['values']\n",
    "        data.append(row)\n",
    "    df = pd.DataFrame(data, columns=columns)\n",
    "    df.to_excel(filename, index=False)\n",
    "    messagebox.showinfo(\"Export\", f\"Exported to {filename}\")\n",
    "\n",
    "def generate_prescription_pdf(patient_name, doctor_name, diagnosis, medicines, advice, followup):\n",
    "    pdf = FPDF()\n",
    "    pdf.add_page()\n",
    "    pdf.set_font(\"Arial\", 'B', 16)\n",
    "    pdf.cell(200, 10, \"Prescription\", ln=1, align='C')\n",
    "    pdf.ln(10)\n",
    "    pdf.set_font(\"Arial\", size=12)\n",
    "    pdf.cell(200, 10, f\"Patient: {patient_name}\", ln=1)\n",
    "    pdf.cell(200, 10, f\"Doctor: {doctor_name}\", ln=1)\n",
    "    pdf.cell(200, 10, f\"Diagnosis: {diagnosis}\", ln=1)\n",
    "    pdf.multi_cell(0, 10, f\"Medicines:\\n{medicines}\")\n",
    "    pdf.multi_cell(0, 10, f\"Advice:\\n{advice}\")\n",
    "    if followup:\n",
    "        pdf.cell(200, 10, f\"Follow-up: {followup}\", ln=1)\n",
    "    filename = f\"prescription_{patient_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf\"\n",
    "    pdf.output(filename)\n",
    "    return filename\n",
    "\n",
    "# ========== LOGIN WINDOW ==========\n",
    "class LoginWindow:\n",
    "    def __init__(self):\n",
    "        self.root = ctk.CTk()\n",
    "        self.root.title(\"Hospital Management System - Login\")\n",
    "        self.root.geometry(\"450x450\")\n",
    "        ctk.set_appearance_mode(\"dark\")\n",
    "        ctk.set_default_color_theme(\"blue\")\n",
    "        \n",
    "        try:\n",
    "            logo_image = ctk.CTkImage(light_image=Image.open(\"hospital_logo.png\"), size=(100, 100))\n",
    "            ctk.CTkLabel(self.root, image=logo_image, text=\"\").pack(pady=20)\n",
    "        except:\n",
    "            ctk.CTkLabel(self.root, text=\"🏥\", font=(\"Arial\", 60)).pack(pady=20)\n",
    "        \n",
    "        frame = ctk.CTkFrame(self.root)\n",
    "        frame.pack(pady=20, padx=50, fill=\"both\", expand=True)\n",
    "        \n",
    "        ctk.CTkLabel(frame, text=\"Hospital Login\", font=(\"Arial\", 24, \"bold\")).pack(pady=20)\n",
    "        ctk.CTkLabel(frame, text=\"Username\").pack(anchor=\"w\")\n",
    "        self.username = ctk.CTkEntry(frame, width=250)\n",
    "        self.username.pack(pady=5)\n",
    "        ctk.CTkLabel(frame, text=\"Password\").pack(anchor=\"w\")\n",
    "        self.password = ctk.CTkEntry(frame, width=250, show=\"*\")\n",
    "        self.password.pack(pady=5)\n",
    "        ctk.CTkButton(frame, text=\"Login\", command=self.do_login).pack(pady=20)\n",
    "        self.password.bind(\"<Return>\", lambda e: self.do_login())\n",
    "        \n",
    "        self.root.mainloop()\n",
    "    \n",
    "    def do_login(self):\n",
    "        uname = self.username.get().strip()\n",
    "        pwd = self.password.get().strip()\n",
    "        user = query_db(\"SELECT u.UserID, u.RoleID, r.RoleName, u.RelatedID FROM Users u JOIN Roles r ON u.RoleID=r.RoleID WHERE u.Username=? AND u.PasswordHash=?\", (uname, pwd), fetch_all=False)\n",
    "        if user:\n",
    "            self.root.destroy()\n",
    "            role = user[2]\n",
    "            related_id = user[3]\n",
    "            app = HospitalApp(uname, role, related_id)\n",
    "        else:\n",
    "            messagebox.showerror(\"Error\", \"Invalid username or password\")\n",
    "\n",
    "# ========== MAIN APPLICATION ==========\n",
    "class HospitalApp:\n",
    "    def __init__(self, username, role, related_id):\n",
    "        self.username = username\n",
    "        self.role = role\n",
    "        self.related_id = related_id\n",
    "        self.root = ctk.CTk()\n",
    "        self.root.title(f\"Hospital Management System - {role}\")\n",
    "        self.root.geometry(\"1400x800\")\n",
    "        \n",
    "        self.status_bar = ctk.CTkLabel(self.root, text=f\"Logged in as {username} ({role})\", height=30, fg_color=\"#2b2b2b\", anchor=\"w\")\n",
    "        self.status_bar.pack(side=\"bottom\", fill=\"x\")\n",
    "        \n",
    "        header = ctk.CTkFrame(self.root, height=80, corner_radius=0, fg_color=\"#1f538d\")\n",
    "        header.pack(fill=\"x\")\n",
    "        try:\n",
    "            logo_img = ctk.CTkImage(light_image=Image.open(\"hospital_logo.png\"), size=(50, 50))\n",
    "            ctk.CTkLabel(header, image=logo_img, text=\"\").pack(side=\"left\", padx=10)\n",
    "        except:\n",
    "            ctk.CTkLabel(header, text=\"🏥\", font=(\"Arial\", 40)).pack(side=\"left\", padx=10)\n",
    "        ctk.CTkLabel(header, text=\"Hospital Management System\", font=(\"Arial\", 24, \"bold\"), text_color=\"white\").pack(side=\"left\", padx=20, pady=20)\n",
    "        \n",
    "        main_container = ctk.CTkFrame(self.root)\n",
    "        main_container.pack(fill=\"both\", expand=True, padx=10, pady=10)\n",
    "        \n",
    "        self.tabview = ctk.CTkTabview(main_container)\n",
    "        self.tabview.pack(fill=\"both\", expand=True)\n",
    "        \n",
    "        if role == \"Admin\":\n",
    "            self.add_admin_tabs()\n",
    "        elif role == \"Doctor\":\n",
    "            self.add_doctor_tabs()\n",
    "        elif role == \"Receptionist\":\n",
    "            self.add_receptionist_tabs()\n",
    "        else:\n",
    "            self.add_patient_tabs()\n",
    "        \n",
    "        self.refresh_all()\n",
    "        self.root.mainloop()\n",
    "    \n",
    "    def add_admin_tabs(self):\n",
    "        self.tabview.add(\"Dashboard\")\n",
    "        self.tabview.add(\"Patients\")\n",
    "        self.tabview.add(\"Doctors\")\n",
    "        self.tabview.add(\"Nurses\")\n",
    "        self.tabview.add(\"Appointments\")\n",
    "        self.tabview.add(\"Prescriptions\")\n",
    "        self.tabview.add(\"Billing\")\n",
    "        self.tabview.add(\"Bed/Ward\")\n",
    "        self.tabview.add(\"Laboratory\")\n",
    "        self.tabview.add(\"Pharmacy\")\n",
    "        self.tabview.add(\"Audit Logs\")\n",
    "        self.tabview.add(\"Users\")\n",
    "        self.setup_dashboard()\n",
    "        self.setup_patients()\n",
    "        self.setup_doctors()\n",
    "        self.setup_nurses()\n",
    "        self.setup_appointments()\n",
    "        self.setup_prescriptions()\n",
    "        self.setup_billing()\n",
    "        self.setup_bed_ward()\n",
    "        self.setup_laboratory()\n",
    "        self.setup_pharmacy()\n",
    "        self.setup_audit_logs()\n",
    "        self.setup_users()\n",
    "    \n",
    "    def add_doctor_tabs(self):\n",
    "        self.tabview.add(\"My Schedule\")\n",
    "        self.tabview.add(\"Appointments\")\n",
    "        self.tabview.add(\"Prescriptions\")\n",
    "        self.tabview.add(\"Patient History\")\n",
    "        self.setup_doctor_schedule()\n",
    "        self.setup_appointments()\n",
    "        self.setup_prescriptions()\n",
    "        self.setup_patient_history()\n",
    "    \n",
    "    def add_receptionist_tabs(self):\n",
    "        self.tabview.add(\"Dashboard\")\n",
    "        self.tabview.add(\"Patients\")\n",
    "        self.tabview.add(\"Appointments\")\n",
    "        self.tabview.add(\"Billing\")\n",
    "        self.tabview.add(\"Admissions\")\n",
    "        self.setup_dashboard()\n",
    "        self.setup_patients()\n",
    "        self.setup_appointments()\n",
    "        self.setup_billing()\n",
    "        self.setup_admissions()\n",
    "    \n",
    "    def add_patient_tabs(self):\n",
    "        self.tabview.add(\"My Appointments\")\n",
    "        self.tabview.add(\"My Prescriptions\")\n",
    "        self.tabview.add(\"My Bills\")\n",
    "        self.setup_patient_appointments()\n",
    "        self.setup_patient_prescriptions()\n",
    "        self.setup_patient_bills()\n",
    "    \n",
    "    def refresh_all(self):\n",
    "        if self.role == \"Admin\":\n",
    "            self.refresh_patients()\n",
    "            self.refresh_doctors()\n",
    "            self.refresh_nurses()\n",
    "            self.refresh_appointments()\n",
    "            self.refresh_patient_doctor_combos()\n",
    "            self.refresh_completed_appointments()\n",
    "            self.update_dashboard()\n",
    "            self.refresh_beds()\n",
    "            self.refresh_lab_orders()\n",
    "            self.refresh_medicines()\n",
    "            self.refresh_audit()\n",
    "            self.refresh_users()\n",
    "        elif self.role == \"Doctor\":\n",
    "            self.refresh_doctor_schedule()\n",
    "            self.refresh_appointments()\n",
    "            self.refresh_patient_history()\n",
    "        elif self.role == \"Receptionist\":\n",
    "            self.refresh_patients()\n",
    "            self.refresh_appointments()\n",
    "            self.update_dashboard()\n",
    "            self.refresh_admissions()\n",
    "        else:\n",
    "            self.refresh_patient_appointments()\n",
    "            self.refresh_patient_prescriptions()\n",
    "            self.refresh_patient_bills()\n",
    "        self.status_bar.configure(text=\"Data refreshed\")\n",
    "    \n",
    "    # ---------- DASHBOARD ----------\n",
    "    def setup_dashboard(self):\n",
    "        tab = self.tabview.tab(\"Dashboard\")\n",
    "        stats_frame = ctk.CTkFrame(tab)\n",
    "        stats_frame.pack(fill=\"x\", padx=20, pady=20)\n",
    "        \n",
    "        self.patient_count_label = ctk.CTkLabel(stats_frame, text=\"Patients: 0\", font=(\"Arial\", 18, \"bold\"), fg_color=\"#2b5a8c\", corner_radius=10, width=200, height=80)\n",
    "        self.patient_count_label.pack(side=\"left\", padx=20, pady=10)\n",
    "        self.doctor_count_label = ctk.CTkLabel(stats_frame, text=\"Doctors: 0\", font=(\"Arial\", 18, \"bold\"), fg_color=\"#2b5a8c\", corner_radius=10, width=200, height=80)\n",
    "        self.doctor_count_label.pack(side=\"left\", padx=20, pady=10)\n",
    "        self.appointment_count_label = ctk.CTkLabel(stats_frame, text=\"Today's Appointments: 0\", font=(\"Arial\", 18, \"bold\"), fg_color=\"#2b5a8c\", corner_radius=10, width=280, height=80)\n",
    "        self.appointment_count_label.pack(side=\"left\", padx=20, pady=10)\n",
    "        self.revenue_label = ctk.CTkLabel(stats_frame, text=\"Today's Revenue: $0\", font=(\"Arial\", 18, \"bold\"), fg_color=\"#2b5a8c\", corner_radius=10, width=250, height=80)\n",
    "        self.revenue_label.pack(side=\"left\", padx=20, pady=10)\n",
    "        \n",
    "        chart_frame = ctk.CTkFrame(tab)\n",
    "        chart_frame.pack(fill=\"both\", expand=True, padx=20, pady=20)\n",
    "        self.fig, self.ax = plt.subplots(figsize=(6, 4), facecolor=\"#2b2b2b\")\n",
    "        self.ax.set_facecolor(\"#2b2b2b\")\n",
    "        self.ax.tick_params(colors=\"white\")\n",
    "        self.ax.set_title(\"Appointments per Day (Last 7 Days)\", color=\"white\")\n",
    "        self.canvas = FigureCanvasTkAgg(self.fig, master=chart_frame)\n",
    "        self.canvas.get_tk_widget().pack(fill=\"both\", expand=True)\n",
    "        \n",
    "        upcoming_frame = ctk.CTkFrame(tab)\n",
    "        upcoming_frame.pack(fill=\"both\", expand=True, padx=20, pady=10)\n",
    "        ctk.CTkLabel(upcoming_frame, text=\"Upcoming Appointments\", font=(\"Arial\", 16, \"bold\")).pack(anchor=\"w\", padx=10)\n",
    "        self.upcoming_tree = ttk.Treeview(upcoming_frame, columns=(\"Date\",\"Patient\",\"Doctor\",\"Time\"), show=\"headings\", height=6)\n",
    "        for c in (\"Date\",\"Patient\",\"Doctor\",\"Time\"):\n",
    "            self.upcoming_tree.heading(c, text=c)\n",
    "        self.upcoming_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        self.update_dashboard()\n",
    "    \n",
    "    def update_dashboard(self):\n",
    "        patients = query_db(\"SELECT COUNT(*) FROM Patients\")\n",
    "        if patients: self.patient_count_label.configure(text=f\"Patients: {patients[0][0]}\")\n",
    "        doctors = query_db(\"SELECT COUNT(*) FROM Doctors\")\n",
    "        if doctors: self.doctor_count_label.configure(text=f\"Doctors: {doctors[0][0]}\")\n",
    "        today = datetime.today().strftime(\"%Y-%m-%d\")\n",
    "        today_apps = query_db(\"SELECT COUNT(*) FROM Appointments WHERE AppointmentDate=?\", (today,))\n",
    "        if today_apps: self.appointment_count_label.configure(text=f\"Today's Appointments: {today_apps[0][0]}\")\n",
    "        revenue = query_db(\"SELECT SUM(PaidAmount) FROM Bills WHERE PaymentDate=?\", (today,))\n",
    "        if revenue and revenue[0][0]:\n",
    "            self.revenue_label.configure(text=f\"Today's Revenue: ${revenue[0][0]:.2f}\")\n",
    "        else: self.revenue_label.configure(text=\"Today's Revenue: $0\")\n",
    "        \n",
    "        dates, counts = [], []\n",
    "        for i in range(6, -1, -1):\n",
    "            d = datetime.today() - timedelta(days=i)\n",
    "            cnt = query_db(\"SELECT COUNT(*) FROM Appointments WHERE AppointmentDate=?\", (d.strftime(\"%Y-%m-%d\"),))\n",
    "            dates.append(d.strftime(\"%m/%d\"))\n",
    "            counts.append(cnt[0][0] if cnt else 0)\n",
    "        self.ax.clear()\n",
    "        self.ax.bar(dates, counts, color=\"#1f538d\")\n",
    "        self.ax.set_title(\"Appointments per Day (Last 7 Days)\", color=\"white\")\n",
    "        self.ax.set_xlabel(\"Date\", color=\"white\")\n",
    "        self.ax.set_ylabel(\"Count\", color=\"white\")\n",
    "        self.ax.tick_params(colors=\"white\")\n",
    "        self.fig.tight_layout()\n",
    "        self.canvas.draw()\n",
    "        \n",
    "        for row in self.upcoming_tree.get_children():\n",
    "            self.upcoming_tree.delete(row)\n",
    "        upcoming = query_db(\"\"\"SELECT TOP 10 AppointmentDate, p.FullName, d.FullName, StartTime\n",
    "                               FROM Appointments a JOIN Patients p ON a.PatientID=p.PatientID JOIN Doctors d ON a.DoctorID=d.DoctorID\n",
    "                               WHERE AppointmentDate >= ? AND Status='Scheduled' ORDER BY AppointmentDate\"\"\", (today,))\n",
    "        if upcoming:\n",
    "            for u in upcoming: self.upcoming_tree.insert(\"\", \"end\", values=sanitize_row(u))\n",
    "    \n",
    "    # ---------- PATIENTS ----------\n",
    "    def setup_patients(self):\n",
    "        tab = self.tabview.tab(\"Patients\")\n",
    "        top = ctk.CTkFrame(tab)\n",
    "        top.pack(fill=\"x\", padx=10, pady=10)\n",
    "        ctk.CTkLabel(top, text=\"Search:\").pack(side=\"left\", padx=5)\n",
    "        self.patient_search = ctk.CTkEntry(top, width=200)\n",
    "        self.patient_search.pack(side=\"left\", padx=5)\n",
    "        self.patient_search.bind(\"<KeyRelease>\", lambda e: self.refresh_patients())\n",
    "        ctk.CTkButton(top, text=\"➕ Add Patient\", command=self.add_patient).pack(side=\"right\", padx=5)\n",
    "        \n",
    "        self.patient_tree = ttk.Treeview(tab, columns=(\"ID\",\"Name\",\"Phone\",\"Email\",\"BloodGroup\"), show=\"headings\")\n",
    "        for c in (\"ID\",\"Name\",\"Phone\",\"Email\",\"BloodGroup\"):\n",
    "            self.patient_tree.heading(c, text=c)\n",
    "        self.patient_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        \n",
    "        btn_frame = ctk.CTkFrame(tab)\n",
    "        btn_frame.pack(fill=\"x\", padx=10, pady=10)\n",
    "        ctk.CTkButton(btn_frame, text=\"✏️ Edit\", command=self.edit_patient).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btn_frame, text=\"🗑️ Delete\", command=self.delete_patient).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btn_frame, text=\"📊 Export to Excel\", command=lambda: export_to_excel(self.patient_tree, \"patients.xlsx\")).pack(side=\"left\", padx=5)\n",
    "        self.refresh_patients()\n",
    "    \n",
    "    def refresh_patients(self):\n",
    "        for row in self.patient_tree.get_children():\n",
    "            self.patient_tree.delete(row)\n",
    "        search = self.patient_search.get().strip()\n",
    "        q = \"SELECT PatientID, FullName, Phone, Email, BloodGroup FROM Patients\"\n",
    "        if search:\n",
    "            q += f\" WHERE FullName LIKE '%{search}%' OR Phone LIKE '%{search}%'\"\n",
    "        rows = query_db(q)\n",
    "        for r in rows:\n",
    "            self.patient_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def add_patient(self):\n",
    "        self.patient_form()\n",
    "    \n",
    "    def edit_patient(self):\n",
    "        sel = self.patient_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select a patient\")\n",
    "            return\n",
    "        pid = self.patient_tree.item(sel[0])['values'][0]\n",
    "        self.patient_form(pid)\n",
    "    \n",
    "    def patient_form(self, pid=None):\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Patient Form\")\n",
    "        win.geometry(\"500x600\")\n",
    "        fields = {}\n",
    "        labels = [\"Full Name\",\"Date of Birth (YYYY-MM-DD)\",\"Gender\",\"Phone\",\"Email\",\"Address\",\"Blood Group\"]\n",
    "        for i, lbl in enumerate(labels):\n",
    "            ctk.CTkLabel(win, text=lbl).grid(row=i, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "            e = ctk.CTkEntry(win, width=300)\n",
    "            e.grid(row=i, column=1, padx=10, pady=5)\n",
    "            fields[lbl] = e\n",
    "        if pid:\n",
    "            data = query_db(\"SELECT FullName,DateOfBirth,Gender,Phone,Email,Address,BloodGroup FROM Patients WHERE PatientID=?\", (pid,), fetch_all=False)\n",
    "            if data:\n",
    "                fields[\"Full Name\"].insert(0, data[0])\n",
    "                fields[\"Date of Birth (YYYY-MM-DD)\"].insert(0, str(data[1]))\n",
    "                fields[\"Gender\"].insert(0, data[2])\n",
    "                fields[\"Phone\"].insert(0, data[3])\n",
    "                fields[\"Email\"].insert(0, data[4])\n",
    "                fields[\"Address\"].insert(0, data[5])\n",
    "                fields[\"Blood Group\"].insert(0, data[6])\n",
    "        def save():\n",
    "            vals = [fields[l].get().strip() for l in labels]\n",
    "            if not vals[0] or not vals[3]:\n",
    "                messagebox.showerror(\"Error\", \"Name and Phone required\")\n",
    "                return\n",
    "            if pid:\n",
    "                query_db(\"UPDATE Patients SET FullName=?,DateOfBirth=?,Gender=?,Phone=?,Email=?,Address=?,BloodGroup=? WHERE PatientID=?\", (*vals, pid), fetch_all=False)\n",
    "            else:\n",
    "                query_db(\"INSERT INTO Patients (FullName,DateOfBirth,Gender,Phone,Email,Address,BloodGroup) VALUES (?,?,?,?,?,?,?)\", vals, fetch_all=False)\n",
    "            self.refresh_patients()\n",
    "            win.destroy()\n",
    "            messagebox.showinfo(\"Success\", \"Patient saved\")\n",
    "        ctk.CTkButton(win, text=\"Save\", command=save).grid(row=len(labels), column=0, columnspan=2, pady=20)\n",
    "    \n",
    "    def delete_patient(self):\n",
    "        sel = self.patient_tree.selection()\n",
    "        if not sel: return\n",
    "        if messagebox.askyesno(\"Confirm\", \"Delete patient?\"):\n",
    "            pid = self.patient_tree.item(sel[0])['values'][0]\n",
    "            query_db(\"DELETE FROM Patients WHERE PatientID=?\", (pid,), fetch_all=False)\n",
    "            self.refresh_patients()\n",
    "    \n",
    "    # ---------- DOCTORS ----------\n",
    "    def setup_doctors(self):\n",
    "        tab = self.tabview.tab(\"Doctors\")\n",
    "        top = ctk.CTkFrame(tab)\n",
    "        top.pack(fill=\"x\", padx=10, pady=10)\n",
    "        ctk.CTkButton(top, text=\"➕ Add Doctor\", command=self.add_doctor).pack(side=\"right\", padx=5)\n",
    "        \n",
    "        self.doctor_tree = ttk.Treeview(tab, columns=(\"ID\",\"Name\",\"Specialization\",\"Phone\",\"Fee\"), show=\"headings\")\n",
    "        for c in (\"ID\",\"Name\",\"Specialization\",\"Phone\",\"Fee\"):\n",
    "            self.doctor_tree.heading(c, text=c)\n",
    "        self.doctor_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        \n",
    "        btn_frame = ctk.CTkFrame(tab)\n",
    "        btn_frame.pack(fill=\"x\", padx=10, pady=10)\n",
    "        ctk.CTkButton(btn_frame, text=\"✏️ Edit\", command=self.edit_doctor).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btn_frame, text=\"🗑️ Delete\", command=self.delete_doctor).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btn_frame, text=\"📅 Set Availability\", command=self.open_availability).pack(side=\"left\", padx=5)\n",
    "        self.refresh_doctors()\n",
    "    \n",
    "    def refresh_doctors(self):\n",
    "        for row in self.doctor_tree.get_children():\n",
    "            self.doctor_tree.delete(row)\n",
    "        rows = query_db(\"SELECT d.DoctorID, d.FullName, s.SpecializationName, d.Phone, d.ConsultationFee FROM Doctors d JOIN Specializations s ON d.SpecializationID=s.SpecializationID\")\n",
    "        for r in rows:\n",
    "            self.doctor_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def add_doctor(self):\n",
    "        self.doctor_form()\n",
    "    \n",
    "    def edit_doctor(self):\n",
    "        sel = self.doctor_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select a doctor\")\n",
    "            return\n",
    "        did = self.doctor_tree.item(sel[0])['values'][0]\n",
    "        self.doctor_form(did)\n",
    "    \n",
    "    def doctor_form(self, did=None):\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Doctor Form\")\n",
    "        win.geometry(\"500x600\")\n",
    "        fields = {}\n",
    "        labels = [\"Full Name\",\"Phone\",\"Email\",\"Qualification\",\"Consultation Fee\"]\n",
    "        for i, lbl in enumerate(labels):\n",
    "            ctk.CTkLabel(win, text=lbl).grid(row=i, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "            e = ctk.CTkEntry(win, width=300)\n",
    "            e.grid(row=i, column=1, padx=10, pady=5)\n",
    "            fields[lbl] = e\n",
    "        ctk.CTkLabel(win, text=\"Specialization\").grid(row=len(labels), column=0, padx=10, pady=5, sticky=\"w\")\n",
    "        specs = [\"Cardiologist\",\"Dermatologist\",\"Neurologist\",\"Pediatrician\",\"Orthopedic\",\"General Physician\"]\n",
    "        spec_var = tk.StringVar(value=specs[0])\n",
    "        spec_combo = ttk.Combobox(win, textvariable=spec_var, values=specs, state=\"readonly\", width=30)\n",
    "        spec_combo.grid(row=len(labels), column=1, padx=10, pady=5)\n",
    "        if did:\n",
    "            data = query_db(\"SELECT d.FullName, d.Phone, d.Email, d.Qualification, d.ConsultationFee, s.SpecializationName FROM Doctors d JOIN Specializations s ON d.SpecializationID=s.SpecializationID WHERE d.DoctorID=?\", (did,), fetch_all=False)\n",
    "            if data:\n",
    "                fields[\"Full Name\"].insert(0, data[0])\n",
    "                fields[\"Phone\"].insert(0, data[1])\n",
    "                fields[\"Email\"].insert(0, data[2])\n",
    "                fields[\"Qualification\"].insert(0, data[3])\n",
    "                fields[\"Consultation Fee\"].insert(0, str(data[4]))\n",
    "                spec_var.set(data[5])\n",
    "        def save():\n",
    "            vals = [fields[l].get().strip() for l in labels]\n",
    "            spec = spec_var.get()\n",
    "            if not vals[0] or not spec:\n",
    "                messagebox.showerror(\"Error\", \"Name and specialization required\")\n",
    "                return\n",
    "            spec_row = query_db(\"SELECT SpecializationID FROM Specializations WHERE SpecializationName=?\", (spec,))\n",
    "            if spec_row:\n",
    "                spec_id = spec_row[0][0]\n",
    "            else:\n",
    "                query_db(\"INSERT INTO Specializations (SpecializationName) VALUES (?)\", (spec,), fetch_all=False)\n",
    "                spec_id = query_db(\"SELECT SpecializationID FROM Specializations WHERE SpecializationName=?\", (spec,), fetch_all=False)[0][0]\n",
    "            fee = float(vals[4]) if vals[4] else 0\n",
    "            if did:\n",
    "                query_db(\"UPDATE Doctors SET FullName=?, SpecializationID=?, Phone=?, Email=?, Qualification=?, ConsultationFee=? WHERE DoctorID=?\", (vals[0], spec_id, vals[1], vals[2], vals[3], fee, did), fetch_all=False)\n",
    "            else:\n",
    "                query_db(\"INSERT INTO Doctors (FullName,SpecializationID,Phone,Email,Qualification,ConsultationFee) VALUES (?,?,?,?,?,?)\", (vals[0], spec_id, vals[1], vals[2], vals[3], fee), fetch_all=False)\n",
    "            self.refresh_doctors()\n",
    "            win.destroy()\n",
    "            messagebox.showinfo(\"Success\", \"Doctor saved\")\n",
    "        ctk.CTkButton(win, text=\"Save\", command=save).grid(row=len(labels)+1, column=0, columnspan=2, pady=20)\n",
    "    \n",
    "    def delete_doctor(self):\n",
    "        sel = self.doctor_tree.selection()\n",
    "        if not sel: return\n",
    "        if messagebox.askyesno(\"Confirm\", \"Delete doctor?\"):\n",
    "            did = self.doctor_tree.item(sel[0])['values'][0]\n",
    "            query_db(\"DELETE FROM Doctors WHERE DoctorID=?\", (did,), fetch_all=False)\n",
    "            self.refresh_doctors()\n",
    "    \n",
    "    def open_availability(self):\n",
    "        sel = self.doctor_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select a doctor\")\n",
    "            return\n",
    "        doc_id = self.doctor_tree.item(sel[0])['values'][0]\n",
    "        doc_name = self.doctor_tree.item(sel[0])['values'][1]\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(f\"Availability for {doc_name}\")\n",
    "        win.geometry(\"400x450\")\n",
    "        \n",
    "        ctk.CTkLabel(win, text=\"Day of Week:\").pack(pady=5)\n",
    "        days = [\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\",\"Sunday\"]\n",
    "        day_var = tk.StringVar(value=days[0])\n",
    "        day_menu = ctk.CTkOptionMenu(win, variable=day_var, values=days)\n",
    "        day_menu.pack(pady=5)\n",
    "        \n",
    "        ctk.CTkLabel(win, text=\"Start Time (HH:MM):\").pack(pady=5)\n",
    "        start_entry = ctk.CTkEntry(win, width=150)\n",
    "        start_entry.pack()\n",
    "        start_entry.insert(0, \"09:00\")\n",
    "        \n",
    "        ctk.CTkLabel(win, text=\"End Time (HH:MM):\").pack(pady=5)\n",
    "        end_entry = ctk.CTkEntry(win, width=150)\n",
    "        end_entry.pack()\n",
    "        end_entry.insert(0, \"17:00\")\n",
    "        \n",
    "        ctk.CTkLabel(win, text=\"Slot Duration (minutes):\").pack(pady=5)\n",
    "        dur_entry = ctk.CTkEntry(win, width=100)\n",
    "        dur_entry.pack()\n",
    "        dur_entry.insert(0, \"30\")\n",
    "        \n",
    "        def save():\n",
    "            day_name = day_var.get()\n",
    "            day_map = {\"Monday\":0,\"Tuesday\":1,\"Wednesday\":2,\"Thursday\":3,\"Friday\":4,\"Saturday\":5,\"Sunday\":6}\n",
    "            day_int = day_map[day_name]\n",
    "            start = start_entry.get().strip()\n",
    "            end = end_entry.get().strip()\n",
    "            dur = int(dur_entry.get().strip()) if dur_entry.get().strip() else 30\n",
    "            if not start or not end:\n",
    "                messagebox.showerror(\"Error\", \"Enter times\")\n",
    "                return\n",
    "            query_db(\"INSERT INTO DoctorAvailability (DoctorID, DayOfWeek, StartTime, EndTime, SlotDuration) VALUES (?,?,?,?,?)\", (doc_id, day_int, start, end, dur), fetch_all=False)\n",
    "            messagebox.showinfo(\"Success\", f\"Availability added for {day_name}\")\n",
    "            win.destroy()\n",
    "        \n",
    "        ctk.CTkButton(win, text=\"Save\", command=save).pack(pady=20)\n",
    "    \n",
    "    # ---------- NURSES ----------\n",
    "    def setup_nurses(self):\n",
    "        tab = self.tabview.tab(\"Nurses\")\n",
    "        top = ctk.CTkFrame(tab)\n",
    "        top.pack(fill=\"x\", padx=10, pady=10)\n",
    "        ctk.CTkButton(top, text=\"➕ Add Nurse\", command=self.add_nurse).pack(side=\"right\", padx=5)\n",
    "        \n",
    "        self.nurse_tree = ttk.Treeview(tab, columns=(\"ID\",\"Name\",\"Phone\",\"Email\",\"Doctor\"), show=\"headings\")\n",
    "        for c in (\"ID\",\"Name\",\"Phone\",\"Email\",\"Doctor\"):\n",
    "            self.nurse_tree.heading(c, text=c)\n",
    "        self.nurse_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        \n",
    "        btn_frame = ctk.CTkFrame(tab)\n",
    "        btn_frame.pack(fill=\"x\", padx=10, pady=10)\n",
    "        ctk.CTkButton(btn_frame, text=\"✏️ Edit\", command=self.edit_nurse).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btn_frame, text=\"🗑️ Delete\", command=self.delete_nurse).pack(side=\"left\", padx=5)\n",
    "        self.refresh_nurses()\n",
    "    \n",
    "    def refresh_nurses(self):\n",
    "        for row in self.nurse_tree.get_children():\n",
    "            self.nurse_tree.delete(row)\n",
    "        rows = query_db(\"SELECT n.NurseID, n.FullName, n.Phone, n.Email, d.FullName FROM Nurses n LEFT JOIN Doctors d ON n.AssignedDoctorID = d.DoctorID\")\n",
    "        for r in rows:\n",
    "            self.nurse_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def add_nurse(self):\n",
    "        self.nurse_form()\n",
    "    \n",
    "    def edit_nurse(self):\n",
    "        sel = self.nurse_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select a nurse\")\n",
    "            return\n",
    "        nid = self.nurse_tree.item(sel[0])['values'][0]\n",
    "        self.nurse_form(nid)\n",
    "    \n",
    "    def nurse_form(self, nid=None):\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Nurse Form\")\n",
    "        win.geometry(\"500x500\")\n",
    "        fields = {}\n",
    "        labels = [\"Full Name\",\"Phone\",\"Email\"]\n",
    "        for i, lbl in enumerate(labels):\n",
    "            ctk.CTkLabel(win, text=lbl).grid(row=i, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "            e = ctk.CTkEntry(win, width=300)\n",
    "            e.grid(row=i, column=1, padx=10, pady=5)\n",
    "            fields[lbl] = e\n",
    "        ctk.CTkLabel(win, text=\"Assign to Doctor (optional)\").grid(row=len(labels), column=0, padx=10, pady=5, sticky=\"w\")\n",
    "        docs = query_db(\"SELECT DoctorID, FullName FROM Doctors\")\n",
    "        doc_list = [\"\"] + [f\"{d[0]} - {d[1]}\" for d in docs]\n",
    "        doc_var = tk.StringVar()\n",
    "        doc_combo = ttk.Combobox(win, textvariable=doc_var, values=doc_list, state=\"readonly\", width=30)\n",
    "        doc_combo.grid(row=len(labels), column=1, padx=10, pady=5)\n",
    "        if nid:\n",
    "            data = query_db(\"SELECT FullName, Phone, Email, AssignedDoctorID FROM Nurses WHERE NurseID=?\", (nid,), fetch_all=False)\n",
    "            if data:\n",
    "                fields[\"Full Name\"].insert(0, data[0])\n",
    "                fields[\"Phone\"].insert(0, data[1])\n",
    "                fields[\"Email\"].insert(0, data[2])\n",
    "                if data[3]:\n",
    "                    doc_name = query_db(\"SELECT FullName FROM Doctors WHERE DoctorID=?\", (data[3],), fetch_all=False)[0][0]\n",
    "                    doc_var.set(f\"{data[3]} - {doc_name}\")\n",
    "        def save():\n",
    "            name = fields[\"Full Name\"].get().strip()\n",
    "            if not name:\n",
    "                messagebox.showerror(\"Error\", \"Name required\")\n",
    "                return\n",
    "            phone = fields[\"Phone\"].get().strip()\n",
    "            email = fields[\"Email\"].get().strip()\n",
    "            doc_val = doc_var.get()\n",
    "            assigned = None\n",
    "            if doc_val and \"-\" in doc_val:\n",
    "                assigned = doc_val.split(\" - \")[0]\n",
    "            if nid:\n",
    "                query_db(\"UPDATE Nurses SET FullName=?, Phone=?, Email=?, AssignedDoctorID=? WHERE NurseID=?\", (name, phone, email, assigned, nid), fetch_all=False)\n",
    "            else:\n",
    "                query_db(\"INSERT INTO Nurses (FullName, Phone, Email, AssignedDoctorID) VALUES (?,?,?,?)\", (name, phone, email, assigned), fetch_all=False)\n",
    "            self.refresh_nurses()\n",
    "            win.destroy()\n",
    "            messagebox.showinfo(\"Success\", \"Nurse saved\")\n",
    "        ctk.CTkButton(win, text=\"Save\", command=save).grid(row=len(labels)+1, column=0, columnspan=2, pady=20)\n",
    "    \n",
    "    def delete_nurse(self):\n",
    "        sel = self.nurse_tree.selection()\n",
    "        if not sel: return\n",
    "        if messagebox.askyesno(\"Confirm\", \"Delete nurse?\"):\n",
    "            nid = self.nurse_tree.item(sel[0])['values'][0]\n",
    "            query_db(\"DELETE FROM Nurses WHERE NurseID=?\", (nid,), fetch_all=False)\n",
    "            self.refresh_nurses()\n",
    "    \n",
    "    # ---------- APPOINTMENTS ----------\n",
    "    def setup_appointments(self):\n",
    "        tab = self.tabview.tab(\"Appointments\")\n",
    "        input_frame = ctk.CTkFrame(tab)\n",
    "        input_frame.pack(fill=\"x\", padx=10, pady=10)\n",
    "        \n",
    "        ctk.CTkLabel(input_frame, text=\"Patient:\").grid(row=0, column=0, padx=5, pady=5)\n",
    "        self.app_patient = ttk.Combobox(input_frame, width=30, state=\"readonly\")\n",
    "        self.app_patient.grid(row=0, column=1, padx=5, pady=5)\n",
    "        \n",
    "        ctk.CTkLabel(input_frame, text=\"Doctor:\").grid(row=0, column=2, padx=5, pady=5)\n",
    "        self.app_doctor = ttk.Combobox(input_frame, width=30, state=\"readonly\")\n",
    "        self.app_doctor.grid(row=0, column=3, padx=5, pady=5)\n",
    "        \n",
    "        ctk.CTkLabel(input_frame, text=\"Date (YYYY-MM-DD):\").grid(row=1, column=0, padx=5, pady=5)\n",
    "        self.app_date = ctk.CTkEntry(input_frame, width=20)\n",
    "        self.app_date.grid(row=1, column=1, padx=5, pady=5)\n",
    "        self.app_date.insert(0, datetime.today().strftime(\"%Y-%m-%d\"))\n",
    "        \n",
    "        ctk.CTkLabel(input_frame, text=\"Symptoms:\").grid(row=1, column=2, padx=5, pady=5)\n",
    "        self.app_symptoms = ctk.CTkEntry(input_frame, width=40)\n",
    "        self.app_symptoms.grid(row=1, column=3, padx=5, pady=5)\n",
    "        \n",
    "        ctk.CTkButton(input_frame, text=\"🔍 Check Availability\", command=self.check_availability).grid(row=2, column=0, columnspan=4, pady=10)\n",
    "        \n",
    "        ctk.CTkLabel(tab, text=\"Available Time Slots:\").pack(anchor=\"w\", padx=10)\n",
    "        self.slots_list = tk.Listbox(tab, height=8, bg=\"#2b2b2b\", fg=\"white\")\n",
    "        self.slots_list.pack(fill=\"x\", padx=10, pady=5)\n",
    "        \n",
    "        ctk.CTkButton(tab, text=\"📅 Book Appointment\", command=self.book_appointment).pack(pady=5)\n",
    "        \n",
    "        self.appointments_tree = ttk.Treeview(tab, columns=(\"ID\",\"Patient\",\"Doctor\",\"Date\",\"Time\",\"Status\",\"Symptoms\"), show=\"headings\")\n",
    "        for c in (\"ID\",\"Patient\",\"Doctor\",\"Date\",\"Time\",\"Status\",\"Symptoms\"):\n",
    "            self.appointments_tree.heading(c, text=c)\n",
    "        self.appointments_tree.pack(fill=\"both\", expand=True, padx=10, pady=10)\n",
    "        \n",
    "        btnf = ctk.CTkFrame(tab)\n",
    "        btnf.pack(fill=\"x\", padx=10, pady=10)\n",
    "        ctk.CTkButton(btnf, text=\"🔄 Refresh\", command=self.refresh_appointments).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btnf, text=\"✅ Mark Completed\", command=self.mark_completed).pack(side=\"left\", padx=5)\n",
    "        \n",
    "        self.refresh_patient_doctor_combos()\n",
    "        self.refresh_appointments()\n",
    "    \n",
    "    def refresh_patient_doctor_combos(self):\n",
    "        pats = query_db(\"SELECT PatientID, FullName FROM Patients\")\n",
    "        if pats:\n",
    "            self.app_patient['values'] = [f\"{p[0]} - {p[1]}\" for p in pats]\n",
    "            self.app_patient.current(0)\n",
    "        else:\n",
    "            self.app_patient['values'] = [\"-- No patients --\"]\n",
    "        docs = query_db(\"SELECT DoctorID, FullName FROM Doctors\")\n",
    "        if docs:\n",
    "            self.app_doctor['values'] = [f\"{d[0]} - {d[1]}\" for d in docs]\n",
    "            self.app_doctor.current(0)\n",
    "        else:\n",
    "            self.app_doctor['values'] = [\"-- No doctors --\"]\n",
    "    \n",
    "    def check_availability(self):\n",
    "        doc_val = self.app_doctor.get()\n",
    "        if not doc_val or doc_val.startswith(\"--\"):\n",
    "            messagebox.showwarning(\"Warning\", \"Select a valid doctor\")\n",
    "            return\n",
    "        doc_id = int(doc_val.split(\" - \")[0])\n",
    "        date = self.app_date.get().strip()\n",
    "        try:\n",
    "            dt = datetime.strptime(date, \"%Y-%m-%d\")\n",
    "            dow = dt.weekday()\n",
    "        except:\n",
    "            messagebox.showerror(\"Error\", \"Invalid date format\")\n",
    "            return\n",
    "        schedule = query_db(\"SELECT StartTime, EndTime, SlotDuration FROM DoctorAvailability WHERE DoctorID=? AND DayOfWeek=?\", (doc_id, dow))\n",
    "        if not schedule:\n",
    "            self.slots_list.delete(0, tk.END)\n",
    "            self.slots_list.insert(tk.END, \"Doctor not available on this day\")\n",
    "            return\n",
    "        start, end, dur = schedule[0]\n",
    "        booked = query_db(\"SELECT StartTime FROM Appointments WHERE DoctorID=? AND AppointmentDate=?\", (doc_id, date))\n",
    "        booked_times = [str(b[0]) for b in booked]\n",
    "        slots = []\n",
    "        cur_t = datetime.strptime(str(start), \"%H:%M:%S\")\n",
    "        end_t = datetime.strptime(str(end), \"%H:%M:%S\")\n",
    "        while cur_t < end_t:\n",
    "            slot = cur_t.strftime(\"%H:%M\")\n",
    "            if slot not in booked_times:\n",
    "                slots.append(slot)\n",
    "            cur_t += timedelta(minutes=dur)\n",
    "        self.slots_list.delete(0, tk.END)\n",
    "        for s in slots:\n",
    "            self.slots_list.insert(tk.END, s)\n",
    "        if not slots:\n",
    "            self.slots_list.insert(tk.END, \"No available slots\")\n",
    "    \n",
    "    def book_appointment(self):\n",
    "        pat_val = self.app_patient.get()\n",
    "        doc_val = self.app_doctor.get()\n",
    "        if pat_val.startswith(\"--\") or doc_val.startswith(\"--\"):\n",
    "            messagebox.showwarning(\"Warning\", \"Select valid patient and doctor\")\n",
    "            return\n",
    "        pat_id = int(pat_val.split(\" - \")[0])\n",
    "        doc_id = int(doc_val.split(\" - \")[0])\n",
    "        date = self.app_date.get().strip()\n",
    "        symptoms = self.app_symptoms.get().strip()\n",
    "        sel = self.slots_list.curselection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select a time slot\")\n",
    "            return\n",
    "        start_time = self.slots_list.get(sel[0])\n",
    "        end_time = (datetime.strptime(start_time, \"%H:%M\") + timedelta(minutes=30)).strftime(\"%H:%M\")\n",
    "        query_db(\"INSERT INTO Appointments (PatientID,DoctorID,AppointmentDate,StartTime,EndTime,Symptoms,Status) VALUES (?,?,?,?,?,?,'Scheduled')\", (pat_id, doc_id, date, start_time, end_time, symptoms), fetch_all=False)\n",
    "        messagebox.showinfo(\"Success\", \"Appointment booked\")\n",
    "        self.refresh_appointments()\n",
    "        self.check_availability()\n",
    "        if self.role in (\"Admin\",\"Receptionist\"):\n",
    "            self.update_dashboard()\n",
    "    \n",
    "    def refresh_appointments(self):\n",
    "        for row in self.appointments_tree.get_children():\n",
    "            self.appointments_tree.delete(row)\n",
    "        rows = query_db(\"SELECT a.AppointmentID, p.FullName, d.FullName, a.AppointmentDate, a.StartTime, a.Status, a.Symptoms FROM Appointments a JOIN Patients p ON a.PatientID=p.PatientID JOIN Doctors d ON a.DoctorID=d.DoctorID ORDER BY a.AppointmentDate DESC\")\n",
    "        for r in rows:\n",
    "            self.appointments_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def mark_completed(self):\n",
    "        sel = self.appointments_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select an appointment\")\n",
    "            return\n",
    "        app_id = self.appointments_tree.item(sel[0])['values'][0]\n",
    "        query_db(\"UPDATE Appointments SET Status='Completed' WHERE AppointmentID=?\", (app_id,), fetch_all=False)\n",
    "        self.refresh_appointments()\n",
    "        self.refresh_completed_appointments()\n",
    "        if self.role in (\"Admin\",\"Receptionist\"):\n",
    "            self.update_dashboard()\n",
    "        messagebox.showinfo(\"Success\", \"Marked as completed\")\n",
    "    \n",
    "    def refresh_completed_appointments(self):\n",
    "        rows = query_db(\"SELECT a.AppointmentID, p.FullName, d.FullName, a.AppointmentDate FROM Appointments a JOIN Patients p ON a.PatientID=p.PatientID JOIN Doctors d ON a.DoctorID=d.DoctorID WHERE a.Status='Completed'\")\n",
    "        vals = [f\"{r[0]} - {r[1]} with Dr. {r[2]} on {r[3]}\" for r in rows]\n",
    "        if hasattr(self, 'pres_app'):\n",
    "            self.pres_app['values'] = vals\n",
    "        if hasattr(self, 'bill_app'):\n",
    "            self.bill_app['values'] = vals\n",
    "    \n",
    "    # ---------- PRESCRIPTIONS ----------\n",
    "    def setup_prescriptions(self):\n",
    "        tab = self.tabview.tab(\"Prescriptions\")\n",
    "        ctk.CTkLabel(tab, text=\"Select Completed Appointment:\").pack(anchor=\"w\", padx=10, pady=5)\n",
    "        self.pres_app = ttk.Combobox(tab, width=80, state=\"readonly\")\n",
    "        self.pres_app.pack(padx=10, pady=5)\n",
    "        ctk.CTkButton(tab, text=\"📋 Load\", command=self.load_prescription).pack(pady=5)\n",
    "        frame = ctk.CTkFrame(tab)\n",
    "        frame.pack(fill=\"both\", expand=True, padx=10, pady=10)\n",
    "        ctk.CTkLabel(frame, text=\"Diagnosis:\").pack(anchor=\"w\")\n",
    "        self.diag_text = tk.Text(frame, height=4, width=80, bg=\"#2b2b2b\", fg=\"white\")\n",
    "        self.diag_text.pack(fill=\"x\", padx=5, pady=5)\n",
    "        ctk.CTkLabel(frame, text=\"Medicines (with dosage):\").pack(anchor=\"w\")\n",
    "        self.med_text = tk.Text(frame, height=6, width=80, bg=\"#2b2b2b\", fg=\"white\")\n",
    "        self.med_text.pack(fill=\"x\", padx=5, pady=5)\n",
    "        ctk.CTkLabel(frame, text=\"Advice:\").pack(anchor=\"w\")\n",
    "        self.adv_text = tk.Text(frame, height=4, width=80, bg=\"#2b2b2b\", fg=\"white\")\n",
    "        self.adv_text.pack(fill=\"x\", padx=5, pady=5)\n",
    "        ctk.CTkLabel(frame, text=\"Follow-up Date (YYYY-MM-DD):\").pack(anchor=\"w\")\n",
    "        self.follow_entry = ctk.CTkEntry(frame, width=150)\n",
    "        self.follow_entry.pack(anchor=\"w\", padx=5, pady=2)\n",
    "        ctk.CTkButton(frame, text=\"💾 Save Prescription\", command=self.save_prescription).pack(pady=10)\n",
    "        self.refresh_completed_appointments()\n",
    "    \n",
    "    def load_prescription(self):\n",
    "        sel = self.pres_app.get()\n",
    "        if not sel:\n",
    "            return\n",
    "        app_id = int(sel.split(\" - \")[0])\n",
    "        data = query_db(\"SELECT Diagnosis,Medicines,Advice,FollowUpDate FROM Prescriptions WHERE AppointmentID=?\", (app_id,), fetch_all=False)\n",
    "        self.diag_text.delete(\"1.0\", tk.END)\n",
    "        self.med_text.delete(\"1.0\", tk.END)\n",
    "        self.adv_text.delete(\"1.0\", tk.END)\n",
    "        self.follow_entry.delete(0, tk.END)\n",
    "        if data:\n",
    "            self.diag_text.insert(\"1.0\", data[0] or \"\")\n",
    "            self.med_text.insert(\"1.0\", data[1] or \"\")\n",
    "            self.adv_text.insert(\"1.0\", data[2] or \"\")\n",
    "            if data[3]:\n",
    "                self.follow_entry.insert(0, str(data[3]))\n",
    "    \n",
    "    def save_prescription(self):\n",
    "        sel = self.pres_app.get()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select an appointment\")\n",
    "            return\n",
    "        app_id = int(sel.split(\" - \")[0])\n",
    "        diag = self.diag_text.get(\"1.0\", tk.END).strip()\n",
    "        med = self.med_text.get(\"1.0\", tk.END).strip()\n",
    "        adv = self.adv_text.get(\"1.0\", tk.END).strip()\n",
    "        follow = self.follow_entry.get().strip() or None\n",
    "        exists = query_db(\"SELECT PrescriptionID FROM Prescriptions WHERE AppointmentID=?\", (app_id,))\n",
    "        if exists:\n",
    "            query_db(\"UPDATE Prescriptions SET Diagnosis=?, Medicines=?, Advice=?, FollowUpDate=? WHERE AppointmentID=?\", (diag, med, adv, follow, app_id), fetch_all=False)\n",
    "        else:\n",
    "            query_db(\"INSERT INTO Prescriptions (AppointmentID, Diagnosis, Medicines, Advice, FollowUpDate) VALUES (?,?,?,?,?)\", (app_id, diag, med, adv, follow), fetch_all=False)\n",
    "        messagebox.showinfo(\"Success\", \"Prescription saved\")\n",
    "    \n",
    "    # ---------- BILLING ----------\n",
    "    def setup_billing(self):\n",
    "        tab = self.tabview.tab(\"Billing\")\n",
    "        ctk.CTkLabel(tab, text=\"Select Completed Appointment:\").pack(anchor=\"w\", padx=10, pady=5)\n",
    "        self.bill_app = ttk.Combobox(tab, width=80, state=\"readonly\")\n",
    "        self.bill_app.pack(padx=10, pady=5)\n",
    "        ctk.CTkButton(tab, text=\"💰 Load Bill\", command=self.load_bill).pack(pady=5)\n",
    "        frame = ctk.CTkFrame(tab)\n",
    "        frame.pack(fill=\"both\", expand=True, padx=10, pady=10)\n",
    "        ctk.CTkLabel(frame, text=\"Consultation Fee ($):\").grid(row=0, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "        self.fee_label = ctk.CTkLabel(frame, text=\"0\")\n",
    "        self.fee_label.grid(row=0, column=1, padx=10, pady=5, sticky=\"w\")\n",
    "        ctk.CTkLabel(frame, text=\"Additional Charges ($):\").grid(row=1, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "        self.extra_entry = ctk.CTkEntry(frame, width=100)\n",
    "        self.extra_entry.grid(row=1, column=1, padx=10, pady=5)\n",
    "        self.extra_entry.bind(\"<KeyRelease>\", lambda e: self.update_total())\n",
    "        ctk.CTkLabel(frame, text=\"Total Amount ($):\").grid(row=2, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "        self.total_label = ctk.CTkLabel(frame, text=\"0\")\n",
    "        self.total_label.grid(row=2, column=1, padx=10, pady=5)\n",
    "        ctk.CTkLabel(frame, text=\"Amount Paid ($):\").grid(row=3, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "        self.paid_entry = ctk.CTkEntry(frame, width=100)\n",
    "        self.paid_entry.grid(row=3, column=1, padx=10, pady=5)\n",
    "        self.paid_entry.bind(\"<KeyRelease>\", lambda e: self.update_status())\n",
    "        ctk.CTkLabel(frame, text=\"Payment Status:\").grid(row=4, column=0, padx=10, pady=5, sticky=\"w\")\n",
    "        self.status_combo = ttk.Combobox(frame, values=[\"Unpaid\",\"Paid\",\"Partial\"], width=15, state=\"readonly\")\n",
    "        self.status_combo.grid(row=4, column=1, padx=10, pady=5)\n",
    "        self.status_combo.set(\"Unpaid\")\n",
    "        ctk.CTkButton(frame, text=\"💾 Save Bill\", command=self.save_bill).grid(row=5, column=0, columnspan=2, pady=20)\n",
    "        self.refresh_completed_appointments()\n",
    "    \n",
    "    def load_bill(self):\n",
    "        sel = self.bill_app.get()\n",
    "        if not sel:\n",
    "            return\n",
    "        app_id = int(sel.split(\" - \")[0])\n",
    "        fee_row = query_db(\"SELECT ConsultationFee FROM Doctors d JOIN Appointments a ON d.DoctorID=a.DoctorID WHERE a.AppointmentID=?\", (app_id,), fetch_all=False)\n",
    "        fee = fee_row[0] if fee_row else 0\n",
    "        self.fee_label.configure(text=str(fee))\n",
    "        bill = query_db(\"SELECT AdditionalCharges, TotalAmount, PaidAmount, PaymentStatus FROM Bills WHERE AppointmentID=?\", (app_id,), fetch_all=False)\n",
    "        if bill:\n",
    "            self.extra_entry.delete(0, tk.END)\n",
    "            self.extra_entry.insert(0, str(bill[0]))\n",
    "            self.total_label.configure(text=str(bill[1]))\n",
    "            self.paid_entry.delete(0, tk.END)\n",
    "            self.paid_entry.insert(0, str(bill[2]))\n",
    "            self.status_combo.set(bill[3])\n",
    "        else:\n",
    "            self.extra_entry.delete(0, tk.END)\n",
    "            self.extra_entry.insert(0, \"0\")\n",
    "            self.paid_entry.delete(0, tk.END)\n",
    "            self.paid_entry.insert(0, \"0\")\n",
    "            self.status_combo.set(\"Unpaid\")\n",
    "            self.update_total()\n",
    "    \n",
    "    def update_total(self):\n",
    "        try:\n",
    "            fee = float(self.fee_label.cget(\"text\"))\n",
    "            extra = float(self.extra_entry.get().strip() or 0)\n",
    "            self.total_label.configure(text=str(fee+extra))\n",
    "        except:\n",
    "            pass\n",
    "        self.update_status()\n",
    "    \n",
    "    def update_status(self):\n",
    "        try:\n",
    "            total = float(self.total_label.cget(\"text\"))\n",
    "            paid = float(self.paid_entry.get().strip() or 0)\n",
    "            if paid >= total:\n",
    "                self.status_combo.set(\"Paid\")\n",
    "            elif paid > 0:\n",
    "                self.status_combo.set(\"Partial\")\n",
    "            else:\n",
    "                self.status_combo.set(\"Unpaid\")\n",
    "        except:\n",
    "            pass\n",
    "    \n",
    "    def save_bill(self):\n",
    "        sel = self.bill_app.get()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select an appointment\")\n",
    "            return\n",
    "        app_id = int(sel.split(\" - \")[0])\n",
    "        fee = float(self.fee_label.cget(\"text\"))\n",
    "        extra = float(self.extra_entry.get().strip() or 0)\n",
    "        total = fee + extra\n",
    "        paid = float(self.paid_entry.get().strip() or 0)\n",
    "        status = self.status_combo.get()\n",
    "        exists = query_db(\"SELECT BillID FROM Bills WHERE AppointmentID=?\", (app_id,))\n",
    "        if exists:\n",
    "            query_db(\"UPDATE Bills SET ConsultationFee=?, AdditionalCharges=?, TotalAmount=?, PaidAmount=?, PaymentStatus=? WHERE AppointmentID=?\", (fee, extra, total, paid, status, app_id), fetch_all=False)\n",
    "        else:\n",
    "            query_db(\"INSERT INTO Bills (AppointmentID, ConsultationFee, AdditionalCharges, TotalAmount, PaidAmount, PaymentStatus) VALUES (?,?,?,?,?,?)\", (app_id, fee, extra, total, paid, status), fetch_all=False)\n",
    "        messagebox.showinfo(\"Success\", \"Bill saved\")\n",
    "    \n",
    "    # ---------- BED/WARD MANAGEMENT ----------\n",
    "    def setup_bed_ward(self):\n",
    "        tab = self.tabview.tab(\"Bed/Ward\")\n",
    "        self.ward_tree = ttk.Treeview(tab, columns=(\"WardID\",\"Ward Name\",\"Type\",\"Total Beds\",\"Occupied\",\"Available\"), show=\"headings\")\n",
    "        self.ward_tree.pack(fill=\"x\", padx=10, pady=5)\n",
    "        for c in (\"WardID\",\"Ward Name\",\"Type\",\"Total Beds\",\"Occupied\",\"Available\"):\n",
    "            self.ward_tree.heading(c, text=c)\n",
    "        self.bed_tree = ttk.Treeview(tab, columns=(\"BedID\",\"Ward\",\"Bed Number\",\"Status\",\"Patient\"), show=\"headings\")\n",
    "        self.bed_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        for c in (\"BedID\",\"Ward\",\"Bed Number\",\"Status\",\"Patient\"):\n",
    "            self.bed_tree.heading(c, text=c)\n",
    "        btnf = ctk.CTkFrame(tab)\n",
    "        btnf.pack(fill=\"x\", padx=10, pady=5)\n",
    "        ctk.CTkButton(btnf, text=\"🛏️ Admit Patient\", command=self.admit_patient).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btnf, text=\"🚪 Discharge Patient\", command=self.discharge_patient).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btnf, text=\"🔄 Refresh\", command=self.refresh_beds).pack(side=\"left\", padx=5)\n",
    "        self.refresh_beds()\n",
    "    \n",
    "    def refresh_beds(self):\n",
    "        for row in self.ward_tree.get_children():\n",
    "            self.ward_tree.delete(row)\n",
    "        wards = query_db(\"SELECT WardID, WardName, WardType FROM Wards\")\n",
    "        for w in wards:\n",
    "            total = query_db(\"SELECT COUNT(*) FROM Beds WHERE WardID=?\", (w[0],))\n",
    "            occ = query_db(\"SELECT COUNT(*) FROM Beds WHERE WardID=? AND IsOccupied=1\", (w[0],))\n",
    "            avail = total[0][0] - occ[0][0]\n",
    "            self.ward_tree.insert(\"\", \"end\", values=sanitize_row((w[0], w[1], w[2], total[0][0], occ[0][0], avail)))\n",
    "        for row in self.bed_tree.get_children():\n",
    "            self.bed_tree.delete(row)\n",
    "        beds = query_db(\"SELECT b.BedID, w.WardName, b.BedNumber, CASE WHEN b.IsOccupied=1 THEN 'Occupied' ELSE 'Available' END, (SELECT TOP 1 p.FullName FROM Admissions a JOIN Patients p ON a.PatientID=p.PatientID WHERE a.BedID=b.BedID AND a.DischargeDate IS NULL) FROM Beds b JOIN Wards w ON b.WardID=w.WardID\")\n",
    "        for b in beds:\n",
    "            self.bed_tree.insert(\"\", \"end\", values=sanitize_row(b))\n",
    "    \n",
    "    def admit_patient(self):\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Admit Patient\")\n",
    "        win.geometry(\"400x300\")\n",
    "        ctk.CTkLabel(win, text=\"Patient:\").pack(pady=5)\n",
    "        pat_combo = ttk.Combobox(win, values=[f\"{p[0]} - {p[1]}\" for p in query_db(\"SELECT PatientID, FullName FROM Patients\")], state=\"readonly\")\n",
    "        pat_combo.pack(pady=5)\n",
    "        ctk.CTkLabel(win, text=\"Bed:\").pack(pady=5)\n",
    "        beds = query_db(\"SELECT BedID, WardName, BedNumber FROM Beds b JOIN Wards w ON b.WardID=w.WardID WHERE IsOccupied=0\")\n",
    "        bed_combo = ttk.Combobox(win, values=[f\"{b[0]} - {b[1]} - {b[2]}\" for b in beds], state=\"readonly\")\n",
    "        bed_combo.pack(pady=5)\n",
    "        def do_admit():\n",
    "            pat_val = pat_combo.get()\n",
    "            bed_val = bed_combo.get()\n",
    "            if not pat_val or not bed_val:\n",
    "                messagebox.showerror(\"Error\", \"Select patient and bed\")\n",
    "                return\n",
    "            pat_id = int(pat_val.split(\" - \")[0])\n",
    "            bed_id = int(bed_val.split(\" - \")[0])\n",
    "            query_db(\"INSERT INTO Admissions (PatientID, BedID) VALUES (?,?)\", (pat_id, bed_id), fetch_all=False)\n",
    "            query_db(\"UPDATE Beds SET IsOccupied=1 WHERE BedID=?\", (bed_id,), fetch_all=False)\n",
    "            messagebox.showinfo(\"Success\", \"Patient admitted\")\n",
    "            win.destroy()\n",
    "            self.refresh_beds()\n",
    "        ctk.CTkButton(win, text=\"Admit\", command=do_admit).pack(pady=20)\n",
    "    \n",
    "    def discharge_patient(self):\n",
    "        sel = self.bed_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select an occupied bed\")\n",
    "            return\n",
    "        bed_id = self.bed_tree.item(sel[0])['values'][0]\n",
    "        if self.bed_tree.item(sel[0])['values'][3] == \"Available\":\n",
    "            messagebox.showwarning(\"Warning\", \"Bed is not occupied\")\n",
    "            return\n",
    "        if messagebox.askyesno(\"Confirm\", \"Discharge patient?\"):\n",
    "            query_db(\"UPDATE Admissions SET DischargeDate=GETDATE() WHERE BedID=? AND DischargeDate IS NULL\", (bed_id,), fetch_all=False)\n",
    "            query_db(\"UPDATE Beds SET IsOccupied=0 WHERE BedID=?\", (bed_id,), fetch_all=False)\n",
    "            messagebox.showinfo(\"Success\", \"Patient discharged\")\n",
    "            self.refresh_beds()\n",
    "    \n",
    "    # ---------- LABORATORY ----------\n",
    "    def setup_laboratory(self):\n",
    "        tab = self.tabview.tab(\"Laboratory\")\n",
    "        self.lab_tree = ttk.Treeview(tab, columns=(\"OrderID\",\"Patient\",\"Test\",\"Ordered Date\",\"Status\",\"Result\"), show=\"headings\")\n",
    "        self.lab_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        for c in (\"OrderID\",\"Patient\",\"Test\",\"Ordered Date\",\"Status\",\"Result\"):\n",
    "            self.lab_tree.heading(c, text=c)\n",
    "        btnf = ctk.CTkFrame(tab)\n",
    "        btnf.pack(fill=\"x\", padx=10, pady=5)\n",
    "        ctk.CTkButton(btnf, text=\"➕ New Lab Order\", command=self.new_lab_order).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btnf, text=\"🔬 Enter Result\", command=self.enter_lab_result).pack(side=\"left\", padx=5)\n",
    "        self.refresh_lab_orders()\n",
    "    \n",
    "    def refresh_lab_orders(self):\n",
    "        for row in self.lab_tree.get_children():\n",
    "            self.lab_tree.delete(row)\n",
    "        rows = query_db(\"SELECT lo.OrderID, p.FullName, lt.TestName, lo.OrderedDate, lo.Status, lo.ResultValue FROM LabOrders lo JOIN Appointments a ON lo.AppointmentID=a.AppointmentID JOIN Patients p ON a.PatientID=p.PatientID JOIN LabTests lt ON lo.TestID=lt.TestID ORDER BY lo.OrderedDate DESC\")\n",
    "        for r in rows:\n",
    "            self.lab_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def new_lab_order(self):\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"New Lab Order\")\n",
    "        win.geometry(\"400x300\")\n",
    "        ctk.CTkLabel(win, text=\"Appointment:\").pack(pady=5)\n",
    "        appts = query_db(\"SELECT a.AppointmentID, p.FullName FROM Appointments a JOIN Patients p ON a.PatientID=p.PatientID WHERE a.Status IN ('Scheduled','Completed')\")\n",
    "        app_combo = ttk.Combobox(win, values=[f\"{a[0]} - {a[1]}\" for a in appts], state=\"readonly\")\n",
    "        app_combo.pack(pady=5)\n",
    "        ctk.CTkLabel(win, text=\"Lab Test:\").pack(pady=5)\n",
    "        tests = query_db(\"SELECT TestID, TestName FROM LabTests\")\n",
    "        test_combo = ttk.Combobox(win, values=[f\"{t[0]} - {t[1]}\" for t in tests], state=\"readonly\")\n",
    "        test_combo.pack(pady=5)\n",
    "        def save_order():\n",
    "            app_val = app_combo.get()\n",
    "            test_val = test_combo.get()\n",
    "            if not app_val or not test_val:\n",
    "                messagebox.showerror(\"Error\", \"Select both fields\")\n",
    "                return\n",
    "            app_id = int(app_val.split(\" - \")[0])\n",
    "            test_id = int(test_val.split(\" - \")[0])\n",
    "            query_db(\"INSERT INTO LabOrders (AppointmentID, TestID, Status) VALUES (?,?, 'Pending')\", (app_id, test_id), fetch_all=False)\n",
    "            messagebox.showinfo(\"Success\", \"Lab order created\")\n",
    "            win.destroy()\n",
    "            self.refresh_lab_orders()\n",
    "        ctk.CTkButton(win, text=\"Create Order\", command=save_order).pack(pady=20)\n",
    "    \n",
    "    def enter_lab_result(self):\n",
    "        sel = self.lab_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select an order\")\n",
    "            return\n",
    "        order_id = self.lab_tree.item(sel[0])['values'][0]\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Enter Lab Result\")\n",
    "        win.geometry(\"400x300\")\n",
    "        ctk.CTkLabel(win, text=\"Result Value:\").pack(pady=5)\n",
    "        result_entry = ctk.CTkEntry(win, width=300)\n",
    "        result_entry.pack(pady=5)\n",
    "        ctk.CTkLabel(win, text=\"Is Normal?\").pack(pady=5)\n",
    "        normal_var = tk.BooleanVar(value=True)\n",
    "        ctk.CTkCheckBox(win, text=\"Normal\", variable=normal_var).pack(pady=5)\n",
    "        def save_result():\n",
    "            result = result_entry.get().strip()\n",
    "            if not result:\n",
    "                messagebox.showerror(\"Error\", \"Enter result value\")\n",
    "                return\n",
    "            is_normal = 1 if normal_var.get() else 0\n",
    "            query_db(\"UPDATE LabOrders SET ResultValue=?, IsNormal=?, Status='Completed', ResultDate=GETDATE() WHERE OrderID=?\", (result, is_normal, order_id), fetch_all=False)\n",
    "            messagebox.showinfo(\"Success\", \"Result saved\")\n",
    "            win.destroy()\n",
    "            self.refresh_lab_orders()\n",
    "        ctk.CTkButton(win, text=\"Save Result\", command=save_result).pack(pady=20)\n",
    "    \n",
    "    # ---------- PHARMACY ----------\n",
    "    def setup_pharmacy(self):\n",
    "        tab = self.tabview.tab(\"Pharmacy\")\n",
    "        self.medicine_tree = ttk.Treeview(tab, columns=(\"ID\",\"Medicine\",\"Stock\",\"Price\",\"Reorder Level\"), show=\"headings\")\n",
    "        self.medicine_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        for c in (\"ID\",\"Medicine\",\"Stock\",\"Price\",\"Reorder Level\"):\n",
    "            self.medicine_tree.heading(c, text=c)\n",
    "        btnf = ctk.CTkFrame(tab)\n",
    "        btnf.pack(fill=\"x\", padx=10, pady=5)\n",
    "        ctk.CTkButton(btnf, text=\"➕ Add Medicine\", command=self.add_medicine).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btnf, text=\"📦 Restock\", command=self.restock_medicine).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btnf, text=\"⚠️ Low Stock Alert\", command=self.low_stock_alert).pack(side=\"left\", padx=5)\n",
    "        self.refresh_medicines()\n",
    "    \n",
    "    def refresh_medicines(self):\n",
    "        for row in self.medicine_tree.get_children():\n",
    "            self.medicine_tree.delete(row)\n",
    "        rows = query_db(\"SELECT MedicineID, MedicineName, StockQuantity, Price, ReorderLevel FROM Medicines\")\n",
    "        for r in rows:\n",
    "            self.medicine_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def add_medicine(self):\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Add Medicine\")\n",
    "        win.geometry(\"400x400\")\n",
    "        fields = {}\n",
    "        labels = [\"Medicine Name\",\"Stock Quantity\",\"Price\",\"Reorder Level\"]\n",
    "        for i, lbl in enumerate(labels):\n",
    "            ctk.CTkLabel(win, text=lbl).pack(pady=5)\n",
    "            e = ctk.CTkEntry(win, width=250)\n",
    "            e.pack()\n",
    "            fields[lbl] = e\n",
    "        def save():\n",
    "            vals = [fields[l].get().strip() for l in labels]\n",
    "            if not vals[0]:\n",
    "                messagebox.showerror(\"Error\", \"Name required\")\n",
    "                return\n",
    "            query_db(\"INSERT INTO Medicines (MedicineName, StockQuantity, Price, ReorderLevel) VALUES (?,?,?,?)\",\n",
    "                     (vals[0], int(vals[1]) if vals[1] else 0, float(vals[2]) if vals[2] else 0, int(vals[3]) if vals[3] else 10), fetch_all=False)\n",
    "            messagebox.showinfo(\"Success\", \"Medicine added\")\n",
    "            win.destroy()\n",
    "            self.refresh_medicines()\n",
    "        ctk.CTkButton(win, text=\"Save\", command=save).pack(pady=20)\n",
    "    \n",
    "    def restock_medicine(self):\n",
    "        sel = self.medicine_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select a medicine\")\n",
    "            return\n",
    "        med_id = self.medicine_tree.item(sel[0])['values'][0]\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Restock Medicine\")\n",
    "        win.geometry(\"300x200\")\n",
    "        ctk.CTkLabel(win, text=\"Quantity to add:\").pack(pady=5)\n",
    "        qty_entry = ctk.CTkEntry(win, width=150)\n",
    "        qty_entry.pack(pady=5)\n",
    "        def do_restock():\n",
    "            try:\n",
    "                qty = int(qty_entry.get().strip())\n",
    "                query_db(\"UPDATE Medicines SET StockQuantity = StockQuantity + ? WHERE MedicineID=?\", (qty, med_id), fetch_all=False)\n",
    "                messagebox.showinfo(\"Success\", f\"Added {qty} to stock\")\n",
    "                win.destroy()\n",
    "                self.refresh_medicines()\n",
    "            except:\n",
    "                messagebox.showerror(\"Error\", \"Enter a valid number\")\n",
    "        ctk.CTkButton(win, text=\"Restock\", command=do_restock).pack(pady=20)\n",
    "    \n",
    "    def low_stock_alert(self):\n",
    "        low_stock = query_db(\"SELECT MedicineName, StockQuantity, ReorderLevel FROM Medicines WHERE StockQuantity <= ReorderLevel\")\n",
    "        if low_stock:\n",
    "            msg = \"\\n\".join([f\"{m[0]}: stock {m[1]} (reorder level {m[2]})\" for m in low_stock])\n",
    "            messagebox.showwarning(\"Low Stock Alert\", msg)\n",
    "        else:\n",
    "            messagebox.showinfo(\"Info\", \"All medicines are sufficiently stocked.\")\n",
    "    \n",
    "    # ---------- AUDIT LOGS ----------\n",
    "    def setup_audit_logs(self):\n",
    "        tab = self.tabview.tab(\"Audit Logs\")\n",
    "        self.audit_tree = ttk.Treeview(tab, columns=(\"Timestamp\",\"User\",\"Action\",\"Table\",\"RecordID\"), show=\"headings\")\n",
    "        for c in (\"Timestamp\",\"User\",\"Action\",\"Table\",\"RecordID\"):\n",
    "            self.audit_tree.heading(c, text=c)\n",
    "        self.audit_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        btnf = ctk.CTkFrame(tab)\n",
    "        btnf.pack(fill=\"x\", padx=10, pady=5)\n",
    "        ctk.CTkButton(btnf, text=\"🔄 Refresh\", command=self.refresh_audit).pack(side=\"left\", padx=5)\n",
    "        self.refresh_audit()\n",
    "    \n",
    "    def refresh_audit(self):\n",
    "        for row in self.audit_tree.get_children():\n",
    "            self.audit_tree.delete(row)\n",
    "        rows = query_db(\"SELECT TOP 100 Timestamp, Username, Action, TableName, RecordID FROM AuditLog ORDER BY Timestamp DESC\")\n",
    "        for r in rows:\n",
    "            self.audit_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    # ---------- USERS MANAGEMENT ----------\n",
    "    def setup_users(self):\n",
    "        tab = self.tabview.tab(\"Users\")\n",
    "        self.user_tree = ttk.Treeview(tab, columns=(\"UserID\",\"Username\",\"Role\",\"RelatedID\"), show=\"headings\")\n",
    "        for c in (\"UserID\",\"Username\",\"Role\",\"RelatedID\"):\n",
    "            self.user_tree.heading(c, text=c)\n",
    "        self.user_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        btnf = ctk.CTkFrame(tab)\n",
    "        btnf.pack(fill=\"x\", padx=10, pady=5)\n",
    "        ctk.CTkButton(btnf, text=\"➕ Add User\", command=self.add_user).pack(side=\"left\", padx=5)\n",
    "        ctk.CTkButton(btnf, text=\"🗑️ Delete User\", command=self.delete_user).pack(side=\"left\", padx=5)\n",
    "        self.refresh_users()\n",
    "    \n",
    "    def refresh_users(self):\n",
    "        for row in self.user_tree.get_children():\n",
    "            self.user_tree.delete(row)\n",
    "        rows = query_db(\"SELECT u.UserID, u.Username, r.RoleName, u.RelatedID FROM Users u JOIN Roles r ON u.RoleID=r.RoleID\")\n",
    "        for r in rows:\n",
    "            self.user_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def add_user(self):\n",
    "        win = ctk.CTkToplevel(self.root)\n",
    "        win.title(\"Add User\")\n",
    "        win.geometry(\"400x400\")\n",
    "        ctk.CTkLabel(win, text=\"Username:\").pack(pady=5)\n",
    "        uname = ctk.CTkEntry(win, width=250)\n",
    "        uname.pack()\n",
    "        ctk.CTkLabel(win, text=\"Password:\").pack(pady=5)\n",
    "        pwd = ctk.CTkEntry(win, width=250, show=\"*\")\n",
    "        pwd.pack()\n",
    "        ctk.CTkLabel(win, text=\"Role:\").pack(pady=5)\n",
    "        roles = query_db(\"SELECT RoleID, RoleName FROM Roles\")\n",
    "        role_combo = ttk.Combobox(win, values=[f\"{r[0]} - {r[1]}\" for r in roles], state=\"readonly\")\n",
    "        role_combo.pack()\n",
    "        ctk.CTkLabel(win, text=\"Related ID (DoctorID or PatientID, optional):\").pack(pady=5)\n",
    "        rel_id = ctk.CTkEntry(win, width=250)\n",
    "        rel_id.pack()\n",
    "        def save():\n",
    "            u = uname.get().strip()\n",
    "            p = pwd.get().strip()\n",
    "            rv = role_combo.get()\n",
    "            if not u or not p or not rv:\n",
    "                messagebox.showerror(\"Error\", \"All fields required\")\n",
    "                return\n",
    "            role_id = int(rv.split(\" - \")[0])\n",
    "            rid = rel_id.get().strip()\n",
    "            rid = int(rid) if rid else None\n",
    "            query_db(\"INSERT INTO Users (Username, PasswordHash, RoleID, RelatedID) VALUES (?, ?, ?, ?)\", (u, p, role_id, rid), fetch_all=False)\n",
    "            messagebox.showinfo(\"Success\", \"User added\")\n",
    "            win.destroy()\n",
    "            self.refresh_users()\n",
    "        ctk.CTkButton(win, text=\"Save\", command=save).pack(pady=20)\n",
    "    \n",
    "    def delete_user(self):\n",
    "        sel = self.user_tree.selection()\n",
    "        if not sel:\n",
    "            messagebox.showwarning(\"Warning\", \"Select a user\")\n",
    "            return\n",
    "        user_id = self.user_tree.item(sel[0])['values'][0]\n",
    "        if messagebox.askyesno(\"Confirm\", \"Delete user?\"):\n",
    "            query_db(\"DELETE FROM Users WHERE UserID=?\", (user_id,), fetch_all=False)\n",
    "            self.refresh_users()\n",
    "    \n",
    "    # ---------- DOCTOR SPECIFIC ----------\n",
    "    def setup_doctor_schedule(self):\n",
    "        tab = self.tabview.tab(\"My Schedule\")\n",
    "        self.doc_schedule_tree = ttk.Treeview(tab, columns=(\"Date\",\"Time\",\"Patient\",\"Symptoms\",\"Status\"), show=\"headings\")\n",
    "        for c in (\"Date\",\"Time\",\"Patient\",\"Symptoms\",\"Status\"):\n",
    "            self.doc_schedule_tree.heading(c, text=c)\n",
    "        self.doc_schedule_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        self.refresh_doctor_schedule()\n",
    "    \n",
    "    def refresh_doctor_schedule(self):\n",
    "        for row in self.doc_schedule_tree.get_children():\n",
    "            self.doc_schedule_tree.delete(row)\n",
    "        rows = query_db(\"SELECT AppointmentDate, StartTime, p.FullName, Symptoms, Status FROM Appointments a JOIN Patients p ON a.PatientID=p.PatientID WHERE DoctorID=?\", (self.related_id,))\n",
    "        for r in rows:\n",
    "            self.doc_schedule_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def setup_patient_history(self):\n",
    "        tab = self.tabview.tab(\"Patient History\")\n",
    "        self.history_patient_combo = ttk.Combobox(tab, values=[f\"{p[0]} - {p[1]}\" for p in query_db(\"SELECT PatientID, FullName FROM Patients\")], state=\"readonly\")\n",
    "        self.history_patient_combo.pack(pady=5)\n",
    "        ctk.CTkButton(tab, text=\"Load History\", command=self.load_patient_history).pack(pady=5)\n",
    "        self.history_tree = ttk.Treeview(tab, columns=(\"Date\",\"Doctor\",\"Diagnosis\",\"Medicines\",\"Advice\"), show=\"headings\")\n",
    "        for c in (\"Date\",\"Doctor\",\"Diagnosis\",\"Medicines\",\"Advice\"):\n",
    "            self.history_tree.heading(c, text=c)\n",
    "        self.history_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "    \n",
    "    def load_patient_history(self):\n",
    "        sel = self.history_patient_combo.get()\n",
    "        if not sel:\n",
    "            return\n",
    "        pat_id = int(sel.split(\" - \")[0])\n",
    "        for row in self.history_tree.get_children():\n",
    "            self.history_tree.delete(row)\n",
    "        rows = query_db(\"SELECT a.AppointmentDate, d.FullName, p.Diagnosis, p.Medicines, p.Advice FROM Prescriptions p JOIN Appointments a ON p.AppointmentID=a.AppointmentID JOIN Doctors d ON a.DoctorID=d.DoctorID WHERE a.PatientID=?\", (pat_id,))\n",
    "        for r in rows:\n",
    "            self.history_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    # ---------- RECEPTIONIST SPECIFIC ----------\n",
    "    def setup_admissions(self):\n",
    "        tab = self.tabview.tab(\"Admissions\")\n",
    "        self.admissions_tree = ttk.Treeview(tab, columns=(\"AdmissionID\",\"Patient\",\"Bed\",\"Admit Date\",\"Discharge Date\",\"Diagnosis\"), show=\"headings\")\n",
    "        for c in (\"AdmissionID\",\"Patient\",\"Bed\",\"Admit Date\",\"Discharge Date\",\"Diagnosis\"):\n",
    "            self.admissions_tree.heading(c, text=c)\n",
    "        self.admissions_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        self.refresh_admissions()\n",
    "    \n",
    "    def refresh_admissions(self):\n",
    "        for row in self.admissions_tree.get_children():\n",
    "            self.admissions_tree.delete(row)\n",
    "        rows = query_db(\"SELECT a.AdmissionID, p.FullName, b.BedNumber, a.AdmitDate, a.DischargeDate, a.Diagnosis FROM Admissions a JOIN Patients p ON a.PatientID=p.PatientID JOIN Beds b ON a.BedID=b.BedID\")\n",
    "        for r in rows:\n",
    "            self.admissions_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    # ---------- PATIENT SPECIFIC ----------\n",
    "    def setup_patient_appointments(self):\n",
    "        tab = self.tabview.tab(\"My Appointments\")\n",
    "        self.patient_appt_tree = ttk.Treeview(tab, columns=(\"Date\",\"Doctor\",\"Time\",\"Status\",\"Symptoms\"), show=\"headings\")\n",
    "        for c in (\"Date\",\"Doctor\",\"Time\",\"Status\",\"Symptoms\"):\n",
    "            self.patient_appt_tree.heading(c, text=c)\n",
    "        self.patient_appt_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        self.refresh_patient_appointments()\n",
    "    \n",
    "    def refresh_patient_appointments(self):\n",
    "        for row in self.patient_appt_tree.get_children():\n",
    "            self.patient_appt_tree.delete(row)\n",
    "        rows = query_db(\"SELECT AppointmentDate, d.FullName, StartTime, Status, Symptoms FROM Appointments a JOIN Doctors d ON a.DoctorID=d.DoctorID WHERE PatientID=?\", (self.related_id,))\n",
    "        for r in rows:\n",
    "            self.patient_appt_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def setup_patient_prescriptions(self):\n",
    "        tab = self.tabview.tab(\"My Prescriptions\")\n",
    "        self.patient_pres_tree = ttk.Treeview(tab, columns=(\"Date\",\"Doctor\",\"Diagnosis\",\"Medicines\",\"Advice\"), show=\"headings\")\n",
    "        for c in (\"Date\",\"Doctor\",\"Diagnosis\",\"Medicines\",\"Advice\"):\n",
    "            self.patient_pres_tree.heading(c, text=c)\n",
    "        self.patient_pres_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        self.refresh_patient_prescriptions()\n",
    "    \n",
    "    def refresh_patient_prescriptions(self):\n",
    "        for row in self.patient_pres_tree.get_children():\n",
    "            self.patient_pres_tree.delete(row)\n",
    "        rows = query_db(\"SELECT a.AppointmentDate, d.FullName, p.Diagnosis, p.Medicines, p.Advice FROM Prescriptions p JOIN Appointments a ON p.AppointmentID=a.AppointmentID JOIN Doctors d ON a.DoctorID=d.DoctorID WHERE a.PatientID=?\", (self.related_id,))\n",
    "        for r in rows:\n",
    "            self.patient_pres_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "    \n",
    "    def setup_patient_bills(self):\n",
    "        tab = self.tabview.tab(\"My Bills\")\n",
    "        self.patient_bill_tree = ttk.Treeview(tab, columns=(\"Date\",\"Doctor\",\"Total Amount\",\"Paid\",\"Status\"), show=\"headings\")\n",
    "        for c in (\"Date\",\"Doctor\",\"Total Amount\",\"Paid\",\"Status\"):\n",
    "            self.patient_bill_tree.heading(c, text=c)\n",
    "        self.patient_bill_tree.pack(fill=\"both\", expand=True, padx=10, pady=5)\n",
    "        self.refresh_patient_bills()\n",
    "    \n",
    "    def refresh_patient_bills(self):\n",
    "        for row in self.patient_bill_tree.get_children():\n",
    "            self.patient_bill_tree.delete(row)\n",
    "        rows = query_db(\"SELECT a.AppointmentDate, d.FullName, b.TotalAmount, b.PaidAmount, b.PaymentStatus FROM Bills b JOIN Appointments a ON b.AppointmentID=a.AppointmentID JOIN Doctors d ON a.DoctorID=d.DoctorID WHERE a.PatientID=?\", (self.related_id,))\n",
    "        for r in rows:\n",
    "            self.patient_bill_tree.insert(\"\", \"end\", values=sanitize_row(r))\n",
    "\n",
    "# ========== RUN ==========\n",
    "if __name__ == \"__main__\":\n",
    "    try:\n",
    "        test = pyodbc.connect(CONN_STR)\n",
    "        test.close()\n",
    "        print(\"Database connection successful.\")\n",
    "        login = LoginWindow()\n",
    "    except Exception as e:\n",
    "        print(\"Connection error:\", e)\n",
    "        input(\"Press Enter to exit...\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7fdedbe7-cb89-4595-b206-3404f898f5d5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
